### PR TITLE
Add 'force' option to 'osx_defaults' custom module

### LINKED ISSUE #2: Allow Graceful Failure When Plist Key Does Not Exist
Thanks very much for this work, it is excellent.

Right now using the iTerm2 settings setup doesn't quite work. 

This is because the Ansible extension tries to read the setting before it makes any unneccessary changes using `defaults read` - perfectly sensible. However in the case of trying to set up `PrefsCustomFolder` in `com.googlecode.iterm2` for the first time because this key doesn't exist then it fails.

Under the hood:
```
jacques:mac-ansible alex$ defaults read com.googlecode.iterm2 PrefsCustomFolder
2018-12-30 08:40:08.253 defaults[25584:599521]
The domain/default pair of (com.googlecode.iterm2, PrefsCustomFolder) does not exist
```

Work around for the moment: write `PrefsCustomFolder` manually for the first run through.

Unclear to me what the correct first run behaviour should be: I guess it should be set the key and value in this case without further checks? However this might result in error in writing keys and values that don't exist and are wrongly spelt and so on. Happy to fix this with a quick steer.

### PR DESCRIPTION
**Pull request by adamchainz**
Fixes #2.

### CODE REVIEW

**Comment by adamchainz** [comment]
@conatus please give this a review!

**Comment by conatus** [comment]
Will do!

**Comment by conatus** [comment]
Thanks again for this. Before I test this I guess there is a more fundamental question about the reasonable expectation of what this should do in the default case when the key and value isn't there.

I've got a list of probably 20+ settings here - https://github.com/conatus/mac-ansible/blob/master/roles/mac/files/osx/osx.sh - how many of these don't exist on a fresh Mac OS X machine and would need to be forced? My suspicion is most of them.

If so many of them need to be forced, then should the default be to add them? Considering the usecase here (for me if not the general one) is to use Ansible to manage defaults as a replacement for the common `osx` shell script.

As I've already run this script it is going to be tricky to test this out. So I might need to have a fresh Mac OS machine, which is maybe plausible with CI.

# Test Plan
- [ ] Run it locally on my machine with a handful of settings to test it works - seems like it would from the code!
- [ ] Work out how to run the complete settings set. Does Travis have Mac OS X testing? Maybe.
- [ ] Find out how many have to be forced...
- [ ] Look at Mac OS X documentation to think about what the right decision might be.
- [ ] Work out what to do...

**Comment by conatus** [comment]
The original version of the OSX script many implementation are downstream of, including my own.

https://github.com/mathiasbynens/dotfiles/blob/master/.macos

**Comment by adamchainz** [comment]
I disabled all my OS X settings except iterm2 in b43e9cb7b8a7960f4ae93760ca06d19c78ee9463 . IIRC I was setting up a mac from scratch and due to the new OS version many of the keys for `defaults` had changed and I couldn't be bothered to go look up the new ones. I configured all the OS settings by hand since I'd only captured about 10% of those I cared about in Ansible already.

This repo is mostly an exercise in getting the important bits in place, maximizing return on investment.

Maybe it would be more useful for you to upstream the `osx_defaults` module into Ansible? This PR showed me that the module is from Ansible 1.x days so it may need significant updating, but if you want to take it, please do.

**Comment by conatus** [comment]
https://docs.ansible.com/ansible/latest/modules/osx_defaults_module.html

I didn't realise this was a batteries included Ansible module!

I'll see if the above has the same issue as your extracted version then merge upstream as you say.

**Comment by adamchainz** [comment]
Oh yeah, and it was even there in 1.7 (since https://github.com/ansible/ansible-modules-extras/pull/64 ) so I guess I missed it when I set mine up in 1.8.

Going to close this PR and remove from this repo, yes please take it upstream :)

**Pull request closed without merging**
